[package]
name = "r2ot"
version = "0.1.0"
authors = ["Ronan DEMIMUID"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "2.4.1"
tui = "0.16"
termion = "1.5.6"
native-tls = "0.2.2"
mailparse = "0.13.7"