[package]
name = "R2OT"
version = "0.1.0"
authors = ["Ronan DEMIMUID <ronan.demimuid@rubycat.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
